"""Remove presentation_id column from price

Revision ID: 1461e932ae6f
Revises: 6dc87df97a3b
Create Date: 2023-08-22 18:28:54.620726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1461e932ae6f'
down_revision = '6dc87df97a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_column('presentation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentation_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
