"""empty message

Revision ID: 24981db8e03b
Revises: cb92ac4934cf
Create Date: 2023-08-22 16:29:50.968699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24981db8e03b'
down_revision = 'cb92ac4934cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_value', sa.Float(), nullable=False))  # Renombramos para evitar conflictos con el nombre de la tabla
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('presentation', sa.String(length=50), nullable=False)) # Cambio a tipo String
        batch_op.alter_column('product_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('store_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('value')

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('store_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('product_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column('presentation')
        batch_op.drop_column('date')
        batch_op.drop_column('price_value')  # Recuerda que renombramos esta columna en upgrade

    op.drop_table('presentation')
    # ### end Alembic commands ###

